application: swmobile-game
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_dir: client
- url: /a/.*
  script: main.py
  login: required
  secure: never

derived_file_type:
- python_precompiled
