application: swmobile-game
version: 1
runtime: python
api_version: 1

default_expiration: "5s"

handlers:
- url: /a/.*
  script: main.py
  login: required
  secure: never

- url: /s/.*
  script: main.py
  login: required
  secure: never

- url: /
  script: main.py

- url: /game
  static_files: client/index.html
  upload: client/index.html
  login: required

- url: /
  static_dir: client
  login: required

derived_file_type:
- python_precompiled
